// <auto-generated />
using AlunosApi.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlunosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlunosApi.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            IdAluno = 1,
                            Email = "mariapenha@yahoo.com",
                            Idade = 23,
                            Nome = "Maria da Penha"
                        },
                        new
                        {
                            IdAluno = 2,
                            Email = "manuelbueno@yahoo.com",
                            Idade = 22,
                            Nome = "Manuel Bueno"
                        },
                        new
                        {
                            IdAluno = 3,
                            Email = "jorgeavila@yahoo.com",
                            Idade = 37,
                            Nome = "Jorge Ávila"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
